#!/usr/bin/php
<?php
/**
 * Code generation tool launcher.
 *
 * @category  Tools
 * @package   Tools_Tool
 * @copyright 2010 Monits
 * @license   Copyright (C) 2010. All rights reserved.
 * @version   Release: 1.0.0
 * @link      http://www.zendext.com/
 * @since     1.0.0
 */

require_once 'Zend/Loader/Autoloader.php';

Zend_Loader_Autoloader::getInstance()
  ->registerNamespace('Zend_')
  ->registerNamespace('ZendExt_');

try {
    ZendExt_Tool::execute();
} catch (ZendExt_Tool_Exception $e) {
    echo 'An unexpected error ocurred: ' . $e->getMessage() . "\n";
}
